### ISSUE TITLE
Describe *Shu-Ha-Ri* in a One-Pager for students to use

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#14]
## Background

We want to create and publish our first mental models on GitHub Pages to validate our hypothesis that the way we're approaching it - publicly on the web, easy language, one-pager format will help other students 
(and ourself) to start with their first (work related) projects.

## Acceptance Critera

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to adapted one-pager format (issue)

## Sources

- [DD242: Shu – Ha – Ri, die drei Stufen der Meisterschaft (Juni 2015)](https://www.omnisophie.com/dd242-shu-ha-ri-die-drei-stufen-der-meisterschaft-juni-2015/)
- [5 minutes on SHU HA RI - The Japanese Art of Mastery](https://www.youtube.com/watch?v=bGjPpj7ub_k)
- [Become a Master with Shu-Ha-Ri (PDF)](https://www.acronymat.com/wp-content/uploads/2021/02/shu-ha-ri-poster-min.pdf)

**Comment by GloriaLandsberger** [comment]
Created [Shu-Ha-Ri](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/blob/willi/unter_branch/shu-Ha-Ri/shuHaRiOnePager.md)

**Comment by GloriaLandsberger** [comment]
Created [Schaubild](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/blob/willi/unter_branch/shu-Ha-Ri/Shu-Ha-Ri.svg)
