### ISSUE TITLE
Describe *People-Process-Technology* in a One-Pager for students to use

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#16]
## Background

We want to create and publish our first mental models on GitHub Pages to validate our hypothesis that the way we're approaching it - publicly on the web, easy language, one-pager format will help other students 
(and ourself) to start with their first (work related) projects.

## Acceptance Critera

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to adapted one-pager format (issue)

## Sources

- [People-Tools-Processes (Martin Harizanov)](https://harizanov.com/2019/02/people-tools-processes/)
- [People, Process, Technology: The PPT Framework, Explained](https://www.plutora.com/blog/people-process-technology-ppt-framework-explained)

**Comment by Claiyc** [comment]
Closed by accident.

**Comment by DenRayk** [comment]
Created branch [people_process_technology](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/tree/people_process_technology)
