### ISSUE TITLE
Describe *All Models are Wrong* in a One-Pager for students to use

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#18]
## Background

We want to create and publish our first mental models on GitHub Pages to validate our hypothesis that the way we're approaching it - publicly on the web, easy language, one-pager format will help other students 
(and ourself) to start with their first (work related) projects.

## Acceptance Critera

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to adapted one-pager format (issue)

## Sources

- https://jamesclear.com/all-models-are-wrong
- https://fs.blog/all-models-are-wrong/

**Comment by seali99** [comment]
Created  [All Models Are Wrong, Some Are Useful](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/blob/senad/unter-branch/all_models_are_wrong.md)
