### ISSUE TITLE
Cleanup and harmonize file structure

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#38]
![image](https://user-images.githubusercontent.com/33458/154352286-2c5b8785-f1ef-4be1-8ecb-7a0e41498fb9.png)

## Acceptance Criteria

* Initial test files removed
* Accidental configuration files removed
* Minimal useful readme added
* File structure streamlined (files of folders per mental model?) and documented in wiki when needed

**Comment by Claiyc** [comment]
fixed on master
