### ISSUE TITLE
HandHeadHeart contains raw Urls

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#41]
[HandHeadHeart](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/blob/gh-pages/handsHeadHeart.md) contains raw Urls in the Sources.

Make them valid markdown links. Considers to use markdownlint for checking locally.

**Comment by jens1o** [comment]
caused by #19, I assigned the team which introduced the bug (our team in fact :D)
