### ISSUE TITLE
Describe "What drives us - Autonomy, Mastery, Purpose"

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#42]
## Background

We want to strengthen our muscles by publishing some more mental models on GitHub Pages.

## Acceptance Criteria

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to #13 

## Sources

* [What drives us - Autonomy, Mastery, Purpose](https://sketchplanations.com/autonomy-mastery-purpose)
* [RSA ANIMATE: Drive: The surprising truth about what motivates us](https://youtu.be/u6XAPnuFjJc)
* [Autonomy Mastery Purpose: How to Use Author Daniel Pink’s Framework to Successfully Motivate Your Team](https://toggl.com/blog/autonomy-mastery-purpose)
* [The puzzle of motivation | Dan Pink](https://youtu.be/rrkrvAUbU9Y)

**Comment by Claiyc** [comment]
Please note the issue number 42... Meaning of life... This mental model must be important.
