### ISSUE TITLE
Describe "Context Switching and Productivity"

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#43]
## Background

We want to strengthen our muscles by publishing some more mental models on GitHub Pages.

## Acceptance Criteria

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to #13 

## Sources

* [Context Switching and Productivity](https://blog.doist.com/context-switching/)
* [What multitasking does to your brain | BBC Ideas](https://www.youtube.com/watch?v=tMiyzuO1qMs)
* [5 diagrams that show how context switching saps your productivity](https://www.atlassian.com/blog/productivity/context-switching)

**Comment by GloriaLandsberger** [comment]
Created [context switching](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/blob/sunOrange/onePager/26-contextSwitching/context-switching/contextSwitching.md#)
