### ISSUE TITLE
Allow navigating to the index page from all mental models pages

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#44]
Non-technical readers might not used to use the back browser button. However, they want to be able to read all mental models by going back to the main page and selecting the next one from a list.

## Acceptance Criteria

All mental models pages should have a navigation element (at the top) with a link to the Home/index page. Additional elements can be added easily (minimal menu navigation with an about page etc.)

## Implementation Hints

While we could add a manual link to all mental models pages, the basic idea is to find a way to be able to include a navigational element (the we  might change over time) in the pages. A starting point could be [this](http://jekyllrb.com/docs/step-by-step/05-includes/).

**Comment by Claiyc** [comment]
Fixed by title alredy linking to main page.
