### ISSUE TITLE
Gain expertise about how to work in drawio/diagrams

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#6]
## Background

To start delivering we need to gain expertise in this topic as a whole team. We learn in 2 stages, 1 team extract knowledge and afterwards trains the other teams.

## Acceptance Criteria

* Read through the material and extract the essence of what we need to know for a good start
* Share your expertise with the other teams
* Document as needed
* Be approachable for upcoming questions

## Implementation Hints

* Documentation may happen in the [repo wiki](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki)
* Source: [diagrams.net Documentation](https://www.diagrams.net/doc/)
* Check/use more sources yourself when needed

**Comment by GloriaLandsberger** [comment]
Created [Diagrams.net-Knowledge-Hub](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki/Diagrams.net-Knowledge-Hub)

**Comment by Claiyc** [comment]
No pr found. Seems to be fixed on master.
