### ISSUE TITLE
Improvement: Add a test environment

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#72]
## Background

As we add more content and more advanced behavior to the site, we should make sure that we are able to test and review the whole process before we publish to the live site. #71 is seen as a major change that should be tested before we actually change the live site and affect 1000s of readers 😉.

## Acceptance Criteria

Well, from the PO perspective I would just say: Make sure that the public/master site is never broken in terms of content, navigation etc. How you achieve this is the accountability of the dev team.

## Implementation Hints

* What is the smallest possible solution for this?
* Do we have the necessary skills in the team? Where? What do we need to learn before tackling this?
* What other processes (like branching) etc. are affected by this? Which new processes need to be established?

**Comment by jens1o** [comment]
> Make sure that the public/master site is never broken in terms of content, navigation etc. How you achieve this is the accountability of the dev team.

As far as I know, there is no option to have two GitHub pages generated by one repository.

Still, I could think of a way to achieve the true core of the acceptance criteria: Automated testing. Whenever a pull request is opened, we run a GitHub Action that does the following:

1. When no Markdown page (assuming a Markdown page always correlates with a new mental model) was added in the Pull Request, return and let it pass successfully.
2. Run the following steps:
	1. Make sure the README.md file contains a link to the newly created page (by parsing the .md)
	2. etc. …

This does not account for all possible cases.

**Comment by Claiyc** [comment]
Agreed. Implementing a system like this generally is a good idea. However, the issue I see with this approach is that we won't have an option to review the deployed state ourself before actually releasing. Github Pages often formats md differently than originally displayed in the repo. Issues like that won't be taken in account with that.

A solution I thought of was to implement some sort of live-repository - a dedicated repository always containing a reviewed "release-ready" state. It should be possible to just create a pr on this new repo and compare the main branch of the "dev-repo" (current repo) with the main branch of the "live-repo" (new repo).

Of course the "best" (but also most difficult and over-the-top) solution would be to setup a dedicated webspace handling the entire hosting-process.
