### ISSUE TITLE
The page about Brook's Law doesn't cover the essence of the model

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#74]
Current Situation: Text and graphics talks about lines of communications only

Expected situation: My understanding: The lines of communication is one intermediate step that leads to sth: adding more people to a late project makes it later. That should be reflected in text and in an (additional?) graphic. Still, needs to be a one-pager 😉

**Comment by i3ene** [comment]
#88 pending
