### ISSUE TITLE
Context Switching and Productivity has wrong formatting

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#75]
[The page](https://dhbw-ka-pm.github.io/mentalmodels-for-teams/context-switching/contextSwitching.html) has line breaks where they should be no line breaks, multiple level1 headlines etc. Could have been partially solved using markdownlint, should have been seen in review. Please fix.

How can we improve here?

**Comment by jens1o** [comment]
was fixed by #77 :)
