### ISSUE TITLE
Gain expertise with git/GitHub

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#8]
## Background

To start delivering we need to gain expertise in this topic as a whole team. We learn in 2 stages, 1 team extract knowledge and afterwards trains the other teams.

## Acceptance Criteria

* Read through the material and extract the essence of what we need to know for a good start
* Share your expertise with the other teams
* Document as needed
* Be approachable for upcoming questions

## Implementation Hints

* Documentation may happen in the [repo wiki](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki)
* [Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf)
* Check/use more sources yourself when needed

**Comment by jens1o** [comment]
This issue will track creating a documentation of what we will have presented in-lecture.

**Comment by Claiyc** [comment]
This will be closed once documentation is complete.

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153418324-9e6223ae-fad5-4f30-bd8a-31a143820227.png)

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153418940-c4b3da1e-df50-4002-80e1-7adade5c61c3.png)

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153420904-4bda4017-9ecb-4ce1-b13a-9b24110c9268.png)

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153423155-d12401b3-e3ad-4a2c-9a34-4a1ae92e73af.png)

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153423227-32b4966f-55ea-472c-95f8-9d17ff1e39cd.png)

**Comment by 2000eBe** [comment]
![grafik](https://user-images.githubusercontent.com/98357681/153423559-090a6cd9-368e-4e0c-8d63-5df624019bb1.png)

**Comment by jens1o** [comment]
Wiki page has been created: https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki/Git-Github-Knowledge-Hub
