### ISSUE TITLE
Gain expertise with vscode

### ISSUE THREAD

**Issue by thomykay** [dhbw-ka-pm/mentalmodels-for-teams#9]
## Background

To start delivering we need to gain expertise in this topic as a whole team. We learn in 2 stages, 1 team extract knowledge and afterwards trains the other teams.

## Acceptance Criteria

* Read through the material and extract the essence of what we need to know for a good start
* Share your expertise with the other teams
* Document as needed
* Be approachable for upcoming questions

## Implementation Hints

* Documentation may happen in the [repo wiki](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki)
* Source: [vscode](https://code.visualstudio.com/)
* Check/use more sources yourself when needed

**Comment by i3ene** [comment]
Created [VS-Code-Knowledge-Hub](https://github.com/dhbw-ka-pm/mentalmodels-for-teams/wiki/VS-Code-Knowledge-Hub)

**Comment by Claiyc** [comment]
No pr found, seems to be fixed on master.
